import React from 'react';

import TableEditor from '@/components/alle-ui/table/table-editor';
import { ExtendedColumnDef } from '@/components/alle-ui/table/types/exnteded-column-def';
import PageWrapper from '@/components/hoc/page-wrapper';

interface Superbike {
  id: number;
  brand: string;
  model: string;
  engine: string;
  power: string;
  topSpeed: string;
  price: string;
  year: number;
  status: string;
}

function Page() {
  return (
    <PageWrapper showBackButton title="Basic Table">
      <div className="p-10">
        <TableEditor
          columns={superbikeColumns}
          data={superbikeData}
          config={{ pageSize: superbikeData.length }}
        />
      </div>
    </PageWrapper>
  );
}

export default Page;

export const superbikeColumns: ExtendedColumnDef<Superbike>[] = [
  {
    id: 'id',
    header: 'ID',
    accessorKey: 'id',
    enableSorting: true,
    enableResizing: true,
    size: 80,
    minSize: 60,
    maxSize: 120,
  },
  {
    id: 'brand',
    header: 'Brand',
    accessorKey: 'brand',
    enableSorting: true,
    enableResizing: true,
    size: 120,
    minSize: 80,
    maxSize: 180,
  },
  {
    id: 'model',
    header: 'Model',
    accessorKey: 'model',
    enableSorting: true,
    enableResizing: true,
    size: 140,
    minSize: 100,
    maxSize: 200,
  },
  {
    id: 'engine',
    header: 'Engine',
    accessorKey: 'engine',
    enableResizing: true,
    size: 160,
    minSize: 120,
    maxSize: 220,
  },
  {
    id: 'power',
    header: 'Power',
    accessorKey: 'power',
    enableResizing: true,
    size: 100,
    minSize: 80,
    maxSize: 150,
  },
  {
    id: 'topSpeed',
    header: 'Top Speed',
    accessorKey: 'topSpeed',
    enableResizing: true,
    size: 110,
    minSize: 90,
    maxSize: 160,
  },
  {
    id: 'price',
    header: 'Price',
    accessorKey: 'price',
    enableResizing: true,
    size: 120,
    minSize: 90,
    maxSize: 180,
  },
  {
    id: 'year',
    header: 'Year',
    accessorKey: 'year',
    enableResizing: true,
    size: 80,
    minSize: 60,
    maxSize: 120,
  },
  {
    id: 'status',
    header: 'Status',
    accessorKey: 'status',
    enableResizing: true,
    size: 140,
    minSize: 100,
    maxSize: 200,
  },
];
export const superbikeData: Superbike[] = [
  {
    id: 1,
    brand: 'Ducati',
    model: 'Panigale V4',
    engine: '1103cc V4',
    power: '214 HP',
    topSpeed: '299 km/h',
    price: '$28,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 2,
    brand: 'Kawasaki',
    model: 'Ninja H2',
    engine: '998cc Supercharged',
    power: '228 HP',
    topSpeed: '337 km/h',
    price: '$30,000',
    year: 2022,
    status: 'Available',
  },
  {
    id: 3,
    brand: 'Yamaha',
    model: 'YZF-R1M',
    engine: '998cc Inline-4',
    power: '200 HP',
    topSpeed: '299 km/h',
    price: '$26,000',
    year: 2023,
    status: 'Limited',
  },
  {
    id: 4,
    brand: 'BMW',
    model: 'S1000RR',
    engine: '999cc Inline-4',
    power: '205 HP',
    topSpeed: '303 km/h',
    price: '$25,000',
    year: 2022,
    status: 'Available',
  },
  {
    id: 5,
    brand: 'Aprilia',
    model: 'RSV4 Factory',
    engine: '1099cc V4',
    power: '217 HP',
    topSpeed: '305 km/h',
    price: '$27,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 6,
    brand: 'Honda',
    model: 'CBR1000RR-R SP',
    engine: '999cc Inline-4',
    power: '214 HP',
    topSpeed: '299 km/h',
    price: '$28,500',
    year: 2022,
    status: 'Available',
  },
  {
    id: 7,
    brand: 'Suzuki',
    model: 'GSX-R1000R',
    engine: '999cc Inline-4',
    power: '202 HP',
    topSpeed: '299 km/h',
    price: '$22,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 8,
    brand: 'MV Agusta',
    model: 'F4 RC',
    engine: '998cc Inline-4',
    power: '212 HP',
    topSpeed: '302 km/h',
    price: '$36,000',
    year: 2022,
    status: 'Discontinued',
  },
  {
    id: 9,
    brand: 'Triumph',
    model: 'Daytona Moto2 765',
    engine: '765cc Inline-3',
    power: '128 HP',
    topSpeed: '240 km/h',
    price: '$18,000',
    year: 2020,
    status: 'Limited',
  },
  {
    id: 10,
    brand: 'KTM',
    model: 'RC 8C',
    engine: '889cc Twin',
    power: '128 HP',
    topSpeed: '248 km/h',
    price: '$38,000',
    year: 2023,
    status: 'Limited',
  },
  {
    id: 11,
    brand: 'Ducati',
    model: 'Streetfighter V4',
    engine: '1103cc V4',
    power: '208 HP',
    topSpeed: '299 km/h',
    price: '$22,500',
    year: 2022,
    status: 'Available',
  },
  {
    id: 12,
    brand: 'Kawasaki',
    model: 'ZX-10R',
    engine: '998cc Inline-4',
    power: '203 HP',
    topSpeed: '299 km/h',
    price: '$21,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 13,
    brand: 'Yamaha',
    model: 'MT-10 SP',
    engine: '998cc Inline-4',
    power: '165 HP',
    topSpeed: '250 km/h',
    price: '$17,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 14,
    brand: 'BMW',
    model: 'M 1000 RR',
    engine: '999cc Inline-4',
    power: '212 HP',
    topSpeed: '306 km/h',
    price: '$33,000',
    year: 2023,
    status: 'Limited',
  },
  {
    id: 15,
    brand: 'Aprilia',
    model: 'Tuono V4',
    engine: '1077cc V4',
    power: '175 HP',
    topSpeed: '270 km/h',
    price: '$19,500',
    year: 2022,
    status: 'Available',
  },
  {
    id: 16,
    brand: 'Honda',
    model: 'CBR600RR',
    engine: '599cc Inline-4',
    power: '121 HP',
    topSpeed: '250 km/h',
    price: '$12,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 17,
    brand: 'Suzuki',
    model: 'Hayabusa',
    engine: '1340cc Inline-4',
    power: '190 HP',
    topSpeed: '312 km/h',
    price: '$18,500',
    year: 2023,
    status: 'Available',
  },
  {
    id: 18,
    brand: 'MV Agusta',
    model: 'Brutale 1000 RR',
    engine: '998cc Inline-4',
    power: '208 HP',
    topSpeed: '300 km/h',
    price: '$32,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 19,
    brand: 'Triumph',
    model: 'Speed Triple 1200 RR',
    engine: '1160cc Inline-3',
    power: '177 HP',
    topSpeed: '265 km/h',
    price: '$20,000',
    year: 2022,
    status: 'Available',
  },
  {
    id: 20,
    brand: 'KTM',
    model: '1290 Super Duke R',
    engine: '1301cc V-Twin',
    power: '180 HP',
    topSpeed: '280 km/h',
    price: '$19,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 21,
    brand: 'Ducati',
    model: 'Diavel V4',
    engine: '1158cc V4',
    power: '168 HP',
    topSpeed: '270 km/h',
    price: '$26,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 22,
    brand: 'Kawasaki',
    model: 'Z H2',
    engine: '998cc Supercharged',
    power: '197 HP',
    topSpeed: '299 km/h',
    price: '$19,500',
    year: 2022,
    status: 'Available',
  },
  {
    id: 23,
    brand: 'Yamaha',
    model: 'R7',
    engine: '689cc Twin',
    power: '72 HP',
    topSpeed: '215 km/h',
    price: '$9,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 24,
    brand: 'BMW',
    model: 'R 1250 RS',
    engine: '1254cc Boxer Twin',
    power: '136 HP',
    topSpeed: '250 km/h',
    price: '$17,500',
    year: 2023,
    status: 'Available',
  },
  {
    id: 25,
    brand: 'Aprilia',
    model: 'RS 660',
    engine: '659cc Parallel Twin',
    power: '100 HP',
    topSpeed: '230 km/h',
    price: '$11,500',
    year: 2022,
    status: 'Available',
  },
  {
    id: 26,
    brand: 'Honda',
    model: 'CB1000R',
    engine: '998cc Inline-4',
    power: '143 HP',
    topSpeed: '240 km/h',
    price: '$13,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 27,
    brand: 'Suzuki',
    model: 'GSX-S1000GT',
    engine: '999cc Inline-4',
    power: '150 HP',
    topSpeed: '250 km/h',
    price: '$14,000',
    year: 2022,
    status: 'Available',
  },
  {
    id: 28,
    brand: 'MV Agusta',
    model: 'Superveloce 800',
    engine: '798cc Inline-3',
    power: '147 HP',
    topSpeed: '240 km/h',
    price: '$21,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 29,
    brand: 'Triumph',
    model: 'Trident 660',
    engine: '660cc Inline-3',
    power: '80 HP',
    topSpeed: '200 km/h',
    price: '$8,500',
    year: 2023,
    status: 'Available',
  },
  {
    id: 30,
    brand: 'KTM',
    model: '790 Duke',
    engine: '799cc Parallel Twin',
    power: '105 HP',
    topSpeed: '230 km/h',
    price: '$10,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 31,
    brand: 'Ducati',
    model: 'Monster SP',
    engine: '937cc V-Twin',
    power: '111 HP',
    topSpeed: '240 km/h',
    price: '$15,500',
    year: 2023,
    status: 'Available',
  },
  {
    id: 32,
    brand: 'Kawasaki',
    model: 'ZX-6R',
    engine: '636cc Inline-4',
    power: '127 HP',
    topSpeed: '248 km/h',
    price: '$11,000',
    year: 2022,
    status: 'Available',
  },
  {
    id: 33,

    brand: 'Yamaha',
    model: 'MT-09 SP',
    engine: '890cc Inline-3',
    power: '117 HP',
    topSpeed: '230 km/h',
    price: '$10,500',
    year: 2023,
    status: 'Available',
  },
  {
    id: 34,
    brand: 'BMW',
    model: 'F 900 R',
    engine: '895cc Parallel Twin',
    power: '105 HP',
    topSpeed: '220 km/h',
    price: '$9,500',
    year: 2022,
    status: 'Available',
  },
  {
    id: 35,
    brand: 'Aprilia',
    model: 'Shiver 900',
    engine: '896cc V-Twin',
    power: '95 HP',
    topSpeed: '210 km/h',
    price: '$9,000',
    year: 2021,
    status: 'Discontinued',
  },
  {
    id: 36,
    brand: 'Honda',
    model: 'Hornet 750',
    engine: '755cc Parallel Twin',
    power: '91 HP',
    topSpeed: '220 km/h',
    price: '$9,500',
    year: 2023,
    status: 'Available',
  },
  {
    id: 37,
    brand: 'Suzuki',
    model: 'SV650X',
    engine: '645cc V-Twin',
    power: '76 HP',
    topSpeed: '210 km/h',
    price: '$8,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 38,
    brand: 'MV Agusta',
    model: 'Dragster 800 RR',
    engine: '798cc Inline-3',
    power: '140 HP',
    topSpeed: '244 km/h',
    price: '$22,000',
    year: 2023,
    status: 'Available',
  },
  {
    id: 39,
    brand: 'Triumph',
    model: 'Tiger 900 GT',
    engine: '888cc Inline-3',
    power: '94 HP',
    topSpeed: '210 km/h',
    price: '$14,500',
    year: 2023,
    status: 'Available',
  },
  {
    id: 40,
    brand: 'KTM',
    model: '390 Duke',
    engine: '373cc Single',
    power: '44 HP',
    topSpeed: '170 km/h',
    price: '$6,000',
    year: 2023,
    status: 'Available',
  },
];
